# DE LOS ASOCIADOS

* **Art. 8º**
El número de asociados de la Institución es ilimitado y podrá serlo cualquier persona de existencia visible que llene los requisitos exigidos a tal fin por el presente Estatuto.

* **Art. 9º**
Quienes deseen incorporarse a la Institución deberán solicitarlo por escrito, acompañando referencia autenticada del documento de identidad y fotografías del aspirante y abonando la cuota de ingreso que se fije, y llenando los demás requisitos que se establezcan al efecto. Se establecen las siguientes categorías de socios (para ambos sexos):
    + a) Honorarios.
    + b) Vitalicios.
    + c) Vitalicios Protectores.
    + d) Plenos.
    + e) Plenos “grupo familiar”.
    + f) Cadetes.
    + g) Menores.
    + h) A distancia.
    + i) Adherentes.

* **Art. 10º**
Podrán, ser Socios Honorarios, las personas que, perteneciendo o no a la Institución, se hayan hecho acreedores de esta distinción por haber prestado servicios de extraordinaria importancia a favor de la misma. El título de Socio Honorario será acordado, a propuesta de la Comisión Directiva o a solicitud de trescientos socios con derecho a voto.

* **Art. 11º**
Serán Socios Vitalicios los asociados plenos que hayan cumplido una antigüedad de treinta años consecutivos como tales. En el último trimestre de cada año, los socios vitalicios deberán revalidar su condición compareciendo ante la oficina de asociados munidos del Documento Nacional de Identidad, Libreta de Enrolamiento o Libreta Cívica y fotocopia del mismo, quedando la copia archivada en la oficina de asociados, las que deberán ser puestas a disposición de la Junta Electoral cuando ese organismo lo requiera. La Comisión Directiva deberá intimarlos fehacientemente para que se presenten en la oficina de socios del club, dentro de los 45 días corridos, a cumplir este requisito bajo apercibimiento de excluirlos de los padrones electorales. Asimismo, podrán adquirir esta condición quienes abonen de una sola vez, como mínimo trescientas sesenta (360) cuotas mensuales como Socio Pleno, pudiendo ser fijado el máximo por la Comisión Directiva. Los Socios Vitalicios, tienen los mismos derechos y obligaciones que los Socios Plenos, sin el requisito de la cuota societaria.

<div id="art12">
* **Art. 12º**
Los Vitalicios Protectores son aquellos que, habiendo obtenido la condición de vitalicio, continúen pagando el equivalente al 50% de la cuota social que corresponde al socio pleno. La Comisión Directiva establecerá los reconocimientos y beneficios que se les concederán a los asociados que integren esta categoría.

<div id="art13">
* **Art. 13º**
Serán Socios Plenos los que reúnan las siguientes condiciones:
    + a) Haber cumplido 18 años de edad.
    + b) Llenar la solicitud de ingreso, acompañar su Documento Nacional de Identidad, Libreta de Enrolamiento o Libreta Cívica y fotocopia del mismo.
    + c) Abonar la cuota de ingreso vigente, el costo del carnet social, las mensualidades por adelantado que determine la Comisión Directiva y cumplir los demás requisitos que establezca la Comisión Directiva.
    + d) Los socios Cadetes que hubieren alcanzado la edad que requiere el inciso a).
    + e) Las damas, a consideración de la Comisión Directiva, podrán constituirse en un grupo particular de asociados, pagando una cuota diferenciada, con las mismas obligaciones y derechos de los Socios Plenos comprendidos en el presente artículo.

* **Art. 14º**
El socio Pleno “Grupo Familiar” será el titular y su cónyuge ambos con plenos derechos políticos, de una familia que se suscriba en todas las ramas deportivas, culturales y sociales de la Institución. Podrán ser adherentes de esta categoría, sus hijos (varones y mujeres) hasta la edad de dieciocho años (18). SE establece un tope de 3 hijos, y sobre el excedente de integrantes en la familia, la Comisión Directiva estará facultada a cobrar un extra que puede fijarse en un valor equivalente al 50 % de la cuota de un socio menor por cada integrante que exceda en cantidad. Para ser socio “PLENO GRUPO FAMILIAR” se requiere como mínimo:
    + a) Ser mayor de 18 años
    + b) Firmar la solicitud de ingreso y abonar por adelantado la cuota que fije la Comisión Directiva.
En caso del fallecimiento del titular asume la titularidad su cónyuge. En caso de separación legal, el titular continúa con el mismo número de socio y antigüedad y el cónyuge debe asociarse nuevamente como socio pleno o grupo familiar según corresponda manteniendo la antigüedad.

* **Art. 15º**
Serán Socios Cadetes los que reúnan las siguiente s condiciones:
    + a) Haber cumplido 12 años de edad y ser menor de 18 años;
    + b) Llenar los requisitos exigidos por los incisos b) y c) del [artículo 13º](#art13) del Estatuto, acompañar copia de los documentos probatorios de su edad y llenar la solicitud de ingreso, debidamente autorizada por su representante legal.
Los socios Cadetes al cumplir 18 años pasarán automáticamente a la categoría de Socio Pleno, conservando su antigüedad.

* **Art. 16º**
Podrá ser socio Menor, quien se suscriba en todas las ramas deportivas, culturales y sociales de la institución. Para ello se requiere como mínimo:
    + a) Ser menor de 18 años.
    + b) Firmar la solicitud de ingreso, que será convalidada por el padre, tutor o encargado y abonar por adelantado la cuota que fije la Comisión Directiva. Los socios y socias Menores que hubieren alcanzado la edad de 18 años podrán ingresar a la categoría de socios plenos según el [art. 13º](#art13), manteniendo la antigüedad. En el caso de los menores que forman parte del grupo familiar y cumplen los dieciocho años al hacerse socios plenos no se tomará en cuenta la antigüedad acumulada en el grupo familiar.

* **Art. 17º**
Podrán ser socios “a distancia” todo aquel simpatizante que viviendo fuera del radio urbano de la Ciudad de Córdoba llene los requisitos que establezca la Comisión Directiva y cumpla con los requisitos del [artículo 13º](#art13) . La cuota de los socios a distancia se regirá por los [artículos 68º](#art68) y [123º](#art123) del presente Estatuto.

* **Art. 18º**
Los socios adherentes serán considerados como simpatizantes de la Institución y carecen de derechos políticos; no pudiendo ingresar a la Sede ni participar de la vida social de la Institución; podrán presenciar los partidos de fútbol del equipo de primera división que se disputen en el estadio de la Institución, o en el que nuestra entidad haga las veces de local, con acceso libre a la tribuna popular local, siempre y cuando tenga el pago de la cuota social que corresponda a esta categoría al día.

* **Art. 19º**
La Comisión Directiva podrá rechazar por simple mayoría y sin apelaciones, las solicitudes de ingreso. A su vez se reserva el derecho de admisión.

<div id="art20">
* **Art. 20º**
Los asociados pierden el carácter de tal por renuncia, expulsión o exclusión. Las causas de bajas son:
    + a) renuncia, los que estando al día con tesorería, lo soliciten por escrito a la Comisión Directiva.
    + b) expulsión, se aplicará a los socios incursos en las siguientes faltas; Primero: incumplimiento reiterado de las obligaciones impuestas por el estatuto y los reglamentos internos; Segundo: hacer daño al Club y observar conducta notoriamente perjudicial a los intereses sociales;
    + c) exclusión, se aplicará automáticamente a los que adeuden cuatro meses consecutivos de cuotas.

* **Art. 21º**
Las sanciones previstas a los asociados, así como las de suspensión o amonestación, serán aplicadas por la Comisión Directiva, la que previo a ello deberá intimar al imputado a comparecer a una reunión de dicha Comisión, en la fecha y hora que se le comunicara mediante notificación fehaciente, cursada con una anticipación mínima de diez días corridos y conteniendo la enunciación del hecho punible y de la norma presumiblemente transgredida, como así la invitación a realizar descargos, ofrecer prueba y alegar sobre la producida. La no comparecencia del interesado implica la renuncia al ejercicio del derecho de defensa y la presunción de verosimilitud de los cargos formulados, quedando la Comisión Directiva habilitada para resolver.

* **Art. 22º**
De todas las resoluciones adoptadas en su contra por la Comisión Directiva, el asociado, podrá apelar en primera instancia a la Junta Representativa y en segunda instancia, ante la primera Asamblea que se realice, siempre que se presente el respectivo recurso, en forma escrita ante la Comisión Directiva, dentro de los diez días de notificado de su sanción.

* **Art. 23º**
Los socios dados de baja por renuncia o exclusión, solo podrán ingresar al Club, como socios nuevos, perdiendo la antigüedad anterior.

* **Art. 24º**
Mientras no sea excluido, el socio moroso podrá ponerse al día, conservando así su antigüedad, pagando la totalidad de las cuotas adeudadas a valores actuales.
