# DE LOS DEBERES Y OBLIGACIONES DE LOS ASOCIADOS

<div id="art25">
* **Art. 25º**
Son obligaciones de los asociados:
     + a) Conceder, respetar y cumplir las disposiciones de este Estatuto, reglamentos y resoluciones de la Asamblea y Comisión Directiva, así como mantener el orden y decoro dentro y fuera de las dependencias del Club y en todos los actos que se intervenga.
     + b) Abonar mensualmente y por adelantado las cuotas sociales.
     + c) Tener la obligación moral de aceptar las Comisiones que les encomiendan las Asambleas y Comisiones Directivas.
     + d) Comunicar, dentro de los diez días corridos, todo cambio de domicilio a la Comisión Directiva.

* **Art. 26º**
Las cuotas mensuales de cada categoría de socios, serán fijadas por la Comisión Directiva. Los asociados admitidos en la segunda quincena, pagarán la mensualidad íntegra, lo mismo ocurrirá con los que dejen de pertenecer al club en la primera quincena. El pago de las cuotas sociales vence el 10 de cada mes.

* **Art. 27º**
Están eximidos del pago de las cuotas, los socios comprendidos en la siguiente situación: solicitar por escrito a la Comisión Directiva, una licencia hasta un plazo máximo de seis meses y siempre que la causa invocada se justifique ampliamente. Durante la licencia, el asociado, no podrá concurrir al local social sin razón atendible, pues su presencia en el Club, significará la reanudación de sus obligaciones para con la Institución.

* **Art. 28º**
Los asociados acreditarán su condición de tal, exhibiendo el carnet social con fotografía y el recibo deberá estar al día con Tesorería, cuya presentación es obligatoria para el ingreso en las dependencias del Club y el uso de distintos servicios sociales. El carnet social y los recibos de cuotas son personales e intransferibles.

* **Art. 29º**
Los socios son responsables de cualquier deterioro o perjuicio material que pudieran ocasionar a la Institución, responsabilidad que se extiende a los padres, tutores o guardadores de los socios menores de 18 años de edad.

* **Art. 30º**
Los socios podrán ser suspendidos en sus derechos , por las siguientes causas:
     + a) Por no respetar el Estatuto Social, los Reglamentos internos o las resoluciones dictadas por las Asambleas o la Comisión Directiva.
     + b) Por no mantener el orden y el decoro dentro y fuera de las instalaciones del Club, en todos los actos en que se intervenga.
     + c) Por ceder o facilitar a otras personas el carnet social. Cuando un socio fuera sorprendido faltando al cumplimiento de sus obligaciones, según las prescripciones de los incisos a), b) y c), cualquier miembro de la Comisión Directiva o subcomisión, o en ausencia de esta, el Gerente, o Intendente, podrán resolver el retiro del carnet, elevando el informe pertinente a la Comisión Directiva dentro de las 48 horas. La negativa del socio a entregar la referida credencial, cuando le sea requerida, implicará desacato y agravará su falta. La suspensión podrá ser de hasta seis meses de acuerdo a la gravedad del hecho constatado. El que fuera suspendido por dos veces, a la tercera sanción, será expulsado. El socio abonará igualmente las cuo tas sociales correspondientes al período de suspensión.

* **Art. 31º**
La ignorancia de este Estatuto no servirá de excusa si la excepción no está expresamente autorizada en el mismo, por lo tanto, desde el instante de su ingreso como asociado, declara conocer este Estatuto y se compromete a cumplirlo fielmente.
