# DE LAS AUTORIDADES Y FISCALIZACIÓN DE LA ASOCIACIÓN

`r get_art_meta("36")`
* **Art. 36º**
Son autoridades del Club Instituto Atlético Central Córdoba y como tales deben ser reconocidas y respetadas por los socios, las que a continuación se mencionan:
    + a) La Asamblea constituida estatutariamente.
    + b) La Comisión Directiva y sus miembros.
    + c) La Junta Representativa y sus miembros.
    + d) La Comisión Revisora de Cuentas y sus miembros.
    + e) La Junta Electoral y sus miembros, mientras estén en funciones.
    + f) Los socios que integran las Subcomisiones autorizadas por la Comisión Directiva.

`r get_art_meta("37")`
* **Art. 37º**
Cada órgano es juzgador de sus propios miembros, a quienes puede amonestar o suspender en su carácter de tales, por causas que repute graves. Para la destitución convocará a Asamblea de Socios, por el voto de la mitad más uno de sus integrantes. La destitución de cualquier autoridad del Club es de competencia exclusiva de la Asamblea de Socios y deberá contar con el voto afirmativo de las 2/3 partes del total de los miembros de la misma. El pronunciamiento de este órgano puede limitarse a la destitución en el cargo electivo o extenderse a la expulsión del afectado en su condición de socio.

`r get_art_meta("38")`
* **Art. 38º**
Los miembros de Comisión Directiva, Junta Representativa, Comisión Revisora de Cuentas, y Subcomisiones autorizadas por Comisión Directiva, contra quienes sus propios cuerpos pidan la destitución del cargo, quedarán suspendidos en el desempeño del mismo hasta tanto se pronuncie la Asamblea de Socios.

`r get_art_meta("39")`
* **Art. 39º**
Todo miembro de un órgano puede salvar su responsabilidad respecto de las resoluciones de su cuerpo, dejando expresa constancia en las actas pertinentes de su votación en contra.
