# DE LAS ASAMBLEAS {#cap6}

`r get_art_meta("6", "40")`
* **Art. 40º**
Las Asambleas serán Ordinarias y Extraordinarias, las cuales todas ellas serán soberanas. Las Asambleas Ordinarias se celebrarán anualmente dentro de los 90 días corridos del cierre del ejercicio, y en ellas se incluirá, sin excepción, el siguiente Orden del Día:
    + a) Designación de dos señores socios para firmar el acta.
    + b) Lectura y consideración del acta de la Asamblea anterior.
    + c) Consideración de la memoria, Balance General e Informe de la Comisión Revisora de Cuentas, por el ejercicio anual cerrado el 30 de Junio.
    + d) Consideración de cualquier otro tema incluido en el Orden del día de la Convocatoria. La Asamblea Extraordinaria deberá ser convocada, cuando lo sea a petición de asociados, dentro de los treinta (30) días corridos de formulada la solicitud, o cuando la Comisión Directiva lo creyere conveniente, en cuyo caso efectuará la convocatoria con treinta (30) días corridos de anticipación a la fecha de realización de la misma. Cuando fuera a petición de asociados, la solicitud deberá formularse por escrito y estar suscripta por lo menos por el diez por ciento (10%) de los socios con derecho a voto y con indicación expresa de los motivos del requerimiento.

`r get_art_meta("6", "41")`
* **Art. 41º**
La Comisión Directiva convocará, ineludiblemente, a la Asamblea General Extraordinaria para el tratamiento de la compra, venta o gravamen de bienes inmuebles y para el reemplazo, modificación o corrección del Estatuto, disolución o fusión de la entidad con otra.

`r get_art_meta("6", "42")`
* **Art. 42º**
En las Asambleas no podrán tratarse asuntos no incluidos en la Orden del Día, salvo cuestiones vinculadas a aquellos o a la validez de la convocatoria.

`r get_art_meta("6", "43")`
* **Art. 43º**
Las Asambleas se constituirán, en primera convocatoria, en el día, hora y lugar indicados en la misma, con un número igual a la mitad más uno de los socios con derecho a voz y voto. Si no hubiere número en l a primera citación, media hora después de la fijada para la primera, con cualquier número de socios siempre que no sea inferior al total de miembros titulares que componen la Comisión Directiva, haciendo exclusión -para el recuento- de éstos.

`r get_art_meta("6", "44")`
* **Art. 44º**
La convocatoria, con el Orden del Día confeccionado, deberá hacerse conocer a los asociados por el Boletín Oficial durante el término de tres (3) días, y paralelamente a ello, por notificaciones expuestas en las carteleras de la Sede Social, del Estadio y del Predio La Agustina. Todo ello con treinta (30) días corridos de anticipación al acto

`r get_art_meta("6", "45")`
* **Art. 45º**
Los socios Vitalicios, Vitalicios Protectores, Plenos y los titulares de la categoría Grupo Familiar, sin distinción de sexo, que estuvieren al corriente con Tesorería, podrán participar de las asambleas con derecho a voz y voto, siempre que no se encontraren en uso de licencia o cumpliendo sanciones disciplinarias. A los socios Plenos y titulares de la categoría Grupo Familiar se les exigirá una antigüedad mínima consecutiva e inmediata de un (1) año en el carácter de tales. A los socios que hubieran cambiado de categoría, antes de formulada la convocatoria, se les computará el tiempo que hubiesen pertenecido a otras categorías, siempre que fuese continuo e inmediato.

`r get_art_meta("6", "46")`
* **Art. 46º**
La participación de los socios en las Asambleas será directa y personal, sin que nadie pueda hacerse representar en modo y forma alguna ante ellas, ni retirarse de las mismas sin dar aviso a la Presidencia. Si por el retiro de socios, la Asamblea quedase sin el número mínimo previsto en el [artículo 43º](#art43), así lo declarará la Presidencia dándola por terminada. Que dando algún asunto pendiente, se hará una nueva convocatoria, en la forma y el plazo determinados en este Estatuto.

`r get_art_meta("6", "47")`
* **Art. 47º**
Las asambleas serán presididas por el Presidente o Vice-Presidente 1º; a falta de éstos, por el Vice-Presidente 2º, Secretario, Pro-Secretario o Tesorero y por ausencia de los anteriores citados, será presidida por el socio que la misma Asamblea designare.

`r get_art_meta("6", "48")`
* **Art. 48º**
Ningún socio podrá hacer uso de la palabra sin que ella le fuere concedida por el Presidente, quien deberá acordarla según el siguiente orden:
    + a) Al miembro informante de la Comisión Directiva.
    + b) Al miembro informante en disidencia.
    + c) Al autor del proyecto.
    + d) Al primero que la pidiese entre los demás socios. El Presidente podrá retirar el uso de la palabra al socio que se personalice con otro, al que se aparte del asunto en discusión, lo hiciere en términos inconvenientes o violatorios del Estatuto; deberá suspender diálogos e interrupciones y si se insistiere en los actos precedentemente enumerados podrá hacerlo retirar del recinto, previa votación de la Asamblea en ese sentido.

`r get_art_meta("6", "49")`
* **Art. 49º**
El Presidente podrá cerrar el debate, siempre que la Asamblea no disponga lo contrario a moción de cualquier socio.

`r get_art_meta("6", "50")`
* **Art. 50º**
Las votaciones podrán ser públicas, secretas, nominales o por signos, según determinare el Presidente en cada caso.

`r get_art_meta("6", "51")`
* **Art. 51º**
Las resoluciones se adoptarán por simple mayoría de los socios presentes, salvo los casos previstos por este estatuto que exige proporción mayor. Ningún socio podrá tener más de un voto y los miembros de la Comisión Directiva y Comisión Revisora de cuentas; se abstendrán de hacerlo en los asuntos relacionados con su gestión. Para reconsiderar resoluciones adoptadas en Asambleas anteriores, se podrá hacerlo solamente un a vez, y se requerirá el voto favorable de los dos tercios de los socios presentes en otra Asamblea constituida corno mínimo, con igual o mayor número de asistentes, al de aquella que resolvió el asunto a reconsiderar.

`r get_art_meta("6", "52")`
* **Art. 52º**
Para ser aprobados los puntos que se refieren a la venta y/o gravamen de bienes inmuebles, incorporados al patrimonio del Club, como así también la fusión con otra u otras instituciones similares o no, se requerirá el voto favorable de los dos tercios (2/3) de los socios presentes en la Asamblea Extraordinaria constituida con un quórum mínimo del diez por ciento (10%) de los asociados con derecho a voto.

`r get_art_meta("6", "53")`
* **Art. 53º**
Para la destitución de alguna de las autoridades sancionadas por sus respectivos órganos de gobierno, en virtud del [artículo 37º](#art37) del presente Estatuto Social, se requerirán los dos tercios (2/3) de los votos de los socios presentes en la Asamblea, sea Ordinaria o Extraordinaria, constituida con un quórum mínimo del diez por ciento (10%) de los asociados con derecho a voto.

`r get_art_meta("6", "54")`
* **Art. 54º**
La reforma o cambio de estos Estatutos requerirá la constitución de una Asamblea Extraordinaria, con un quórum mínimo del diez por ciento (10%) de los socios con derecho a voto. La resolución se tomara por simple mayoría. El proyecto de reforma deberá estar a disposición de los asociados, en la Sede Social, con quince (15) días corridos de anticipación a la Asamblea.

`r get_art_meta("6", "55")`
* **Art. 55º**
Las Asambleas podrán pasar a cuarto intermedio por un término que no excederá, en ningún caso, los siete (7) días corridos, a cuyo vencimiento deberán –indefectiblemente- continuar.

`r get_art_meta("6", "56")`
* **Art. 56º**
Las asambleas designarán dos miembros de su seno para firmar el acta juntamente con el Presidente y Secretario.
