# DEL PRESIDENTE

* **Art. 70º**
El Presidente representa a la institución en todos sus actos, ya sean estos legales, deportivos o sociales y ejerce además todas las otras funciones inherentes al cargo y representación que inviste, teniendo las siguientes atribuciones y obligaciones:
    + a) Presidir las Asambleas y reuniones de la Comisión Directiva, como así también, cuando lo creyere conveniente, las sesiones de las Subcomisiones y delegaciones del Club, firmando sus actas.
    + b) Dirigir y organizar las discusiones y votaciones en las asambleas y Comisión Directiva y Subcomisiones que presidiere, resolviendo en todo asunto en caso de empate, con su voto.
    + c) Dirigir a la administración de la Institución, con facultades para intervenir en todos los detalles de ésta.
    + d) Terciar en las discusiones de las asambleas, Comisión Directiva y Subcomisiones, con voz y voto, dejando la Presidencia en estos casos a quien corresponda.
    + e) Ejecutar y hacer ejecutar las resoluciones que adaptaren las Asambleas o Comisión Directiva.
    + f) Firmar los documentos y correspondencia de carácter oficial del Club, Balance y Memoria anuales, como así también las órdenes de pago, chequeras, giros y obligaciones privadas o bancarias, debidamente autorizadas.
    + g) Otorgar, aceptar y firmar los instrumentos públicos y documentos privados y relacionados con los actos o contratos autorizados por la Comisión Directiva o Asambleas.
    + h) Convocar a la Comisión Directiva cuando lo estime conveniente o a pedido de seis (6) miembros de la misma, debiendo en todos los casos indicar el o los asuntos a tratarse. La convocatoria realizada por Secretaría General será dentro de las 48 horas de formuladas las peticiones.
    + i) Convocar a Asamblea cuando lo disponga la Comisión Directiva.
    + j) Resolver por sí solo en cualquier asunto o caso especial que por su urgencia no pudiera ser tratado por la Comisión Directiva, con cargo a rendir cuenta en la primera sesión que ésta celebre.
    + k) Redactar juntamente con el Secretario General, la Memoria anual que debe presentarse a la Asamblea General Ordinaria.
    + l) Intervenir y fiscalizar en cualquier momento las actividades de diverso orden de la sección administrativa y Subcomisiones.
    + m) El Presidente o los Vicepresidentes, en su caso, serán solidariamente responsables con el Tesorero de los pagos que efectúen y con el Secretario General, de los actos que suscriban.
