# DEL VICEPRESIDENTE 2º

`r get_art_meta("73")`
* **Art. 73º**
El Vicepresidente 2º auxiliará y colaborará con e l Presidente y Vicepresidente 1º en el desempeño de sus funciones. En virtud de su cargo, el Vicepresidente 2º supervisará el funcionamiento de las restantes disciplinas que se desarrollen en la Institución, las actividades sociales y presidirá la Junta Representativa.

`r get_art_meta("74")`
* **Art. 74º**
El Vicepresidente 2º reemplazará al Presidente en caso de fallecimiento, ausencia, enfermedad o renuncia del Presidente y Vicepresidente 1º, con las mismas funciones, atribuciones y obligaciones conferidas al Presidente tendrá voz y voto en las Asambleas y reuniones de Comisión Directiva, siempre que no se encuentre en ejercicio de la Presidencia.

`r get_art_meta("75")`
* **Art. 75º**
En caso de renuncia, muerte, ausencia o enfermedad del Presidente, Vicepresidente 1º y Vicepresidente 2º, se hará cargo de la Presidencia, el Vocal de la Comisión Directiva que la misma designe, quien deberá dentro del término de veinte (20) días de haberse hecho cargo llamar a Asamblea Extraordinaria para la elección de Presidente y Vicepresidentes, siempre que no faltase menos de sesenta (60) días corridos para la culminación del período.
