# DEL SECRETARIO GENERAL

* **Art. 76º**
El Secretario General es el colaborador inmediato del Presidente. Sus obligaciones, deberes y atribuciones son:
    + a) Representar al Presidente y Vicepresidente dentro de los locales de la Institución, cuando ellos no estuvieren presentes, así como ejercer la superintendencia inmediata de todo el personal de la Institución.
    + b) Refrendar la firma del Presidente en todos los documentos sociales, con excepción de cheques y libranzas.
    + c) Entender en todos los asuntos, estudiarlos, tratarlos, ordenarlos, someterlos al Presidente y por su intermedio a la Comisión Directiva, excepto los asuntos de Tesorería.
    + d) Asistir a las Asambleas y sesiones de la Comisión Directiva.
    + e) Recibir las solicitudes de socios, dándoles el curso correspondiente y someterlas a la consideración de la Comisión Directiva.
    + f) Recibir y darle curso a toda la correspondencia que llegue a la Institución y redactar o hacer redactar las respuestas y toda la correspondencia a dirigir, conservando copias.
    + g) Cursar la convocatoria a reunión o sesión de la Comisión Directiva para los días que ésta hubiese fijado ordinariamente o cuando el Presidente lo dispusiera de acuerdo al [artículo 67º](#art67) inciso h.
    + h) Expedir, con intervención de la Tesorería, los carnets o credenciales suscribiéndolas con su firma.
    + i) Supervisar los registros de socios, formar o hacer formar con aquellos, el fichero de socios en actividad, de ex socios y establecer el padrón de asociados.
    + j) Tomar a su cargo las actas si por cualquier causa no estuviere el Secretario de Actas e Información Institucional, ni el sustituto, pudiendo para ello, solicitar la colaboración de cualquier miembro de la Comisión Directiva o bien un empleado del Club.
    + k) Recopilar los documentos o informes necesarios para la redacción de la Memoria anual.
    + l) Conservar los trofeos del Club, de los que llevará un registro especial de todos, de cuyos efectos será responsable.
