# DEL TESORERO {#cap13}

`r get_art_meta("13", "79")`
* **Art. 79º**
El Tesorero es el responsable de los fondos y valores de la institución. Cuidará de la integridad de los ingresos y de la procedencia y corrección de los egresos, con arreglo a las disposiciones de este Estatuto, del Reglamento Interno y de las resoluciones de Comisión Directiva que se dicten en su consecuencia.

`r get_art_meta("13", "80")`
* **Art. 80º**
El Tesorero es autoridad competente para intervenir en todo acto u operación relativa a bienes, fondos, valores y demás cosas del patrimonio social. Está facultado para tomar cualquier medida en defensa de los intereses sociales, con cargo de rendir cuenta a Comisión Directiva.

`r get_art_meta("13", "81")`
* **Art. 81º**
Son deberes y atribuciones del Tesorero:
    + a) La recaudación y custodia de todos los fondos de la Institución, llevando los libros de Caja, Diario, Mayor e Inventario y los auxiliares necesarios.
    + b) Verificar los pagos correspondientes a la administración, siempre que ellos hayan sido autorizados por la Comisión Directiva.
    + c) Depositar en el y/o los bancos que indique la Comisión Directiva, en cuenta corriente o en otra forma, a nombre del Club y a la orden conjunta del Presidente, Secretario y Tesorero todos los fondos sociales, a excepción de aquellos que fueren indispensables para atender las necesidades diarias y menores del Club.
    + d) Juntamente con la Comisión Directiva, la iniciativa en materia económica y financiera, elaboración del presupuesto de inversiones y gastos y el cálculo de recurso de cada ejercicio.
    + e) Presentar mensualmente a la Comisión Directiva una balance de caja, acompañando los respectivos comprobantes, y anualmente un balance general y otro de caja al 30 de Abril, dividido en tantas partes como sea necesario. Estos balances deberán ser presentados a la Comisión Directiva dentro de los 30 días de cerrado el ejercicio.
    + f) Firmar conjuntamente con el Presidente, los cheques, libranzas u otros documentos de crédito y por sí los recibos que deba otorgar el club a los socios o particulares.
    + g) Recibir del Secretario General las solicitudes de socios, informar en caso de tratarse de socios morosos, a fin de aplicar el [artículo 20º](#art20).
    + h) Previa autorización de la Comisión Directiva, verificará los pagos correspondientes a la indemnización social u elevará todos los meses la nómina de los socios que se encuentren en estado de cesación de pago.
    + i) Dará cuenta inmediata y por escrito al Presidente, de cualquier irregularidad que observare en los libros o en el manejo de los fondos de la Institución.
    + j) Llevar un registro de pago de la cuota de socios, el que debe estar al día y a disposición de la Comisión Directiva y la Comisión Revisora de Cuentas.
    + k) Realizar todos los demás actos y gestiones propias de la función, siempre que no le estén expresa o implícitamente prohibidos por el Estatuto y/o las reglamentaciones dictadas en su consecuencia.
