# DEL SECRETARIO DE ACTAS E INFORMACIÓN INSTITUCIONAL {#cap15}

`r get_art_meta("15", "84")`
* **Art. 84º**
El Secretario de Actas e Información Institucional será la persona que se encargará de todos los trámites atinentes a la presentación a las reuniones de la Comisión Directiva o Asamblea de Asociados, de las actas que se levantaron y que estarán a su exclusivo cargo. Confeccionará el borrador de las mismas que hará transcribir por empleado de la Institución y verificará luego su pase al libro. Será encargado de su lectura ante quien corresponda y una vez aprobadas, las hará suscribir por el Presidente y el Secretario General si se tratara de Actas de Reuniones de la Comisión Directiva y por dos asociados designados al efecto, si se tratase de Asambleas de asociados. Firmadas las mismas será el responsable a la guarda y control de los libros respectivos.

`r get_art_meta("15", "85")`
* **Art. 85º**
Será asimismo, el Vocero oficial de la Institución, dando a conocer por medio de boletines, la información de más importancia y trascendencia que tenga relación con la vida y marcha del Club. Para el desempeño de tales tareas, podrá designar los colaboradores que estime convenientes y necesarios. Estará igualmente facultado a desautorizar informaciones que no provengan del Presidente, Vice-Presidente y/o Secretario General y que tiendan a deformar la realidad o que conspiren contra los objetivos fundamentales de la Institución.
