# DE LOS VOCALES

* **Art. 92º**
Los Vocales son los miembros de la Comisión Directiva que ésta necesita para sus deliberaciones y consejo, teniendo durante el desarrollo de las mismas, voz y voto. Son deberes y atribuciones de los Vocales:
    + a) Concurrir con puntualidad a las sesiones o reuniones de la Comisión Directiva.
    + b) Desempeñar todas las funciones o comisiones que le encomiende la Comisión Directiva.
    + c) Participar activamente en la vida de la Institución, interesándose en todos sus asuntos.
    + d) Solicitar al Presidente que convoque a sesión de Comisión Directiva de acuerdo al [artículo 68º](#art68) inciso h.
    + e) Hacer guardar el orden en las dependencias de la Institución en colaboración con las demás autoridades o por sí solo en ausencia de aquellas y tomar las medidas que fueren necesarias o de carácter indispensable para salvar dificultades apremiantes con cargo de rendir cuentas a la Comisión Directiva en la primera sesión.
    + f) Ejercer la administración de la Subcomisión a su cargo si fuera designado por la Comisión Directiva, como asimismo, desarrollar las tareas necesarias para la difusión de las actividades que se desarrollan dentro de las esferas de dicha Subcomisión.
    + g) Guardar absoluta reserva sobre cualquier asunto tratado durante las sesiones de la Comisión Directiva o Subcomisiones que integraren.
    + h) Los Vocales tienen la obligación de cumplir con las funciones específicas que les asigne la Comisión Directiva, acorde a lo establecido por el [artículo 59º](#art59); en caso de no hacerlo, serán pasibles de aplicarles las sanciones que establecen los [artículos 66º](#art66) y [69º](#art69) de estos Estatutos, no solo en lo referente a la asistencia, sino también a las faltas cometidas en el desempeño del cargo encomendado.
    + i) Sin perjuicio de lo mencionado en el inciso anterior, la Comisión Directiva designará, de manera idónea, un vocal que deberá participar, por sí o por el representante legal que se designe, en todos los asuntos judiciales en que la Institución sea parte e informar mensualmente a la Comisión Directiva sobre el estado de los mismos.

<div id="art93">
* **Art. 93º**
Las vacantes que se produzcan en los cargos de Vocales por las causas previstas en los artículos precedentes, como así también en caso de renuncia, enfermedad o fallecimiento, se llenará con miembros de la Junta Representativa, respetándose el rango por el cual fueron electos en los comicios de asociados.
