# DE LAS SUBCOMISIONES {#cap20}

`r get_art_meta("20", "94")`
* **Art. 94º**
La Comisión Directiva dispondrá la constitución de las Subcomisiones que estime conveniente para dirigir las distintas actividades y deportes dentro del Club.

`r get_art_meta("20", "95")`
* **Art. 95º**
Las Subcomisiones serán integradas exclusivamente por socios, sin distinción de sexo, mayores de dieciocho (18) años de edad y en las condiciones previstas por el presente Estatuto.

`r get_art_meta("20", "96")`
* **Art. 96º**
Las Subcomisiones serán dirigidas y administradas por un Presidente, un Secretario y un Tesorero, nombrados por la Comisión Directiva a propuesta de los asociados.

`r get_art_meta("20", "97")`
* **Art. 97º**
Cuando un grupo de asociados desee agregar una nueva disciplina deportiva o actividad social o cultural a las ya existentes en la entidad, deberá solicitar por nota dirigida al Presidente y Comisión Directiva, la autorización correspondiente. La mencionada nota deberá estar firmada, como mínimo, por el cinco (5) por ciento del caudal societario del Club, e incluir en la misma, una terna de asociados, de la que la Comisión Directiva elegirá el Presidente, el Secretario y el Tesorero que administrará el nuevo Departamento o Subcomisión.

`r get_art_meta("20", "98")`
* **Art. 98º**
Las Subcomisiones se reunirán por lo menos cada quince (15) días. Su quórum legal será la mitad más uno de sus miembros y las decisiones se tomarán por simple mayoría de votos. Llevarán un libro de actas.

`r get_art_meta("20", "99")`
* **Art. 99º**
Las Subcomisiones, se deben ayuda recíproca. Todo entredicho que se suscitare entre ellas, será resuelto, sin apelación por la Junta Representativa.

`r get_art_meta("20", "100")`
* **Art. 100º**
Las Subcomisiones pueden, con asentimiento de la Comisión Directiva, establecer un aporte monetario con que cada afiliado debe contribuir para solventar los gastos de mantenimiento. Los fondos que en tal concepto se recauden o que por cualquier título ingresen a la Subcomisión, serán administrados por ella, debiendo dar cuenta de su ingreso o inversión a la Comisión Directiva mensualmente.

`r get_art_meta("20", "101")`
* **Art. 101º**
Las atribuciones y obligaciones de las Subcomisiones son:
    + a) Reglamentar la práctica de las actividades sociales y deportivas respectivas.
    + b) Recaudar los fondos necesarios para la práctica de los mismos.
    + c) Concertar justas, torneos, partidos, efectuar reuniones de carácter social, cultural, deportivo o benéfico, con previa autorización de la Comisión Directiva.
    + d) Administrar los fondos recaudados por esos medios.

`r get_art_meta("20", "102")`
* **Art. 102º**
Las Subcomisiones no pueden firmar contratos ni obligar a la Institución. Tampoco pueden nombrar personal a sueldo, debiendo proponerlos a la Comisión Directiva quien otorgará el correspondiente asentimiento y quien a su vez puede declararlo cesante.

`r get_art_meta("20", "103")`
* **Art. 103º**
Al finalizar cada período económico, las Subcomisiones y Departamentos elevarán un balance y memoria detallando las actividades cumplidas durante dicho período.
