# DE LAS ELECCIONES {#cap24}

## De la Junta Electoral

`r get_art_meta("128")`
* **Art. 128º**
La preparación, dirección y contralor de los comicios estará a cargo de una Junta Electoral, integrada de la siguiente forma:
    + a) Un presidente.
    + b) Un Secretario.
    + c) Un Secretario de Actas.

Cada uno de estos tres miembros integrantes se elegirá nominalmente en reunión de la Junta Representativa, citada a tal efecto en forma fehaciente con no menos de 48 hs de anticipación. El número de votos requeridos para ser elegido miembro de la Junta Electoral, será del 70% de los miembros de la Junta Representativa presentes en la reunión. Además integrarán la Junta Electoral, un miembro por cada una de las listas participantes de la elección y que será ratificado o no cuando su lista complete los requisitos establecidos en el [artículo 135º](#art135) para su oficialización. La Junta Electoral será designada cuarenta y cinco (45) días corridos anteriores a la realización de los comicios.

`r get_art_meta("129")`
* **Art. 129º**
El cargo de miembro de la Junta Electoral es inexcusable, debiendo estar empadronado.

`r get_art_meta("130")`
* **Art. 130º**
La Junta Electoral se dictará su reglamento inter no, a menos que, con anterioridad, no hubiese sido aprobado uno por Asamblea de Socios y entenderá todo lo relativo a la preparación de listas, acto electoral, escrutinio definitivo, proclamación de los electos, a cuyo efecto tomará cuantas medidas sean necesarias, siempre que no contraríen el presente Estatuto, debiendo la Comisión Directiva poner a su disposición el personal que estime oportuno.

## Del Padrón de socios

`r get_art_meta("131")`
* **Art. 131º**
La Comisión Directiva, con cuarenta y cinco (45) días corridos de antelación a todo comicio ordinario, confeccionará el padrón de socios con derecho a voto. Gozarán de esta prerrogativa los socios vitalicios y los socios plenos que cuenten con una antigüedad no inferior a un (1) año, contando retrospectivamente, desde la fecha fijada para las elecciones. Para el cómputo de dicha antigüedad se tendrá en cuenta –indistintamente- el tiempo transcurrido como socio pleno, cadete o integrante de grupo familiar.

`r get_art_meta("132")`
* **Art. 132º**
El padrón electoral reunirá los siguientes requisitos:
    + a) Se hará por orden alfabético, indicando número de socio y ultimo domicilio registrado, llevando además una columna para constancia de la emisión del voto y otra para observaciones.
    + b) Se imprimirán las copias necesarias para ser expuestas en la Sede Social, para ser entregadas a la Junta Electoral, a las Agrupaciones de socios que intervengan en la elección, y para las autoridades del comicio en cada mesa.
    + c) Las modificaciones que correspondiera introducir al padrón una vez impreso, responderán –única y exclusivamente- a omisiones o rectificaciones debidamente comprobadas hasta tres (3) días antes de la elección, debiendo en todos los casos labrarse un acta ante la Junta Electoral y dando intervención a los apoderados de las listas participantes en los comicios.

`r get_art_meta("133")`
* **Art. 133º**
Están excluidos del padrón electoral los socios que en el momento de confección se encuentren en uso de licencia o cumpliendo una pena disciplinaria impuesta por la Comisión Directiva. Los inhabilitados para votar que después de la formación del padrón y depuración entraren en el ejercicio de este derecho, presentarán una nota solicitando su inclusión a la Junta Electoral, quien determinará –en cada caso- sobre la procedencia del pedido.

## De la Oficialización de las Listas

`r get_art_meta("134")`
* **Art. 134º**
Diez (10) días antes, por lo menos, de la fecha de realización de la elección, deberán ser presentadas las listas completas de candidatos para ocupar los cargos de la Comisión Directiva, Junta Representativa y Comisión Revisora de Cuentas, las cuales deberán llevar una denominación determinada que no sea igual a otra ya presentada. Ocho (8) días antes, por lo menos, a la realización de la elección, la Junta Electoral deberá oficializar las listas presentadas. En los casos precedentes los plazos se contarán en días co rridos y hasta la cero (0) hora del día de la elección.

`r get_art_meta("135")`
* **Art. 135º**
La oficialización de las listas presentadas no podrá ser negada por la Junta Electoral siempre que llenen los siguientes requisitos:
    + a) Que las solicitudes vengan firmadas por no menos de cien (100) socios electores y que no figuren como candidatos debiendo contener el nombre de las personas que actuarán como Apoderados Generales y fiscales de cada mesa.
    + b) Que todos los candidatos hayan aceptado el carácter de tal, debie ndo la aceptación firmada acompañarse a la solicitud.
    + c) Que los firmantes de la solicitud no hayan suscrito otra presentación. Si figurara alguno en estas condiciones, su firma no será tenida en cuenta.

`r get_art_meta("136")`
* **Art. 136º**
Todo socio que hubiera aceptado su inclusión como candidato y no se hiciere cargo de su puesto, en caso de ser electo, quedará inhabilitado para integrar la Comisión Directiva, Junta Representativa y la Comisión Revisora de Cuentas por el término de cuatro (4) años.

`r get_art_meta("137")`
* **Art. 137º**
Los votos que se dieran a socios cuyas candidaturas no hubieran sido oficializadas no serán computados. Sin embargo, se computará el voto dado a favor de cualquier candidato y cualquiera sea la boleta en que esté incluido y haya sido ésta oficializada y siempre que sean para el cargo postulado oficialmente.

`r get_art_meta("138")`
* **Art. 138º**
Si en una boleta, al practicarse el escrutinio, figuran más nombres de los que corresponde a los cargos que se eligen, se computarán solamente los primeros inscriptos, hasta completar el número establecido.

`r get_art_meta("139")`
* **Art. 139º**
En caso de que uno o más candidatos incluidos en cualquier lista no reuniera los requisitos estatutarios, la lista será devuelta para su ulterior presentación, corregida, dentro del plazo improrrogable de veinticuatro (24) horas.

## Del Acto Electoral

`r get_art_meta("140")`
* **Art. 140º**
Las elecciones se efectuarán en el local del Club , o en el que se designare la Comisión Directiva y en el día fijado, desde las ocho (8) horas hasta las dieciocho (18) horas y se constituirán tantas mesas receptoras de votos como grupos de doscientos cincuenta (250) socios o fracción tenga la Institución, con derecho a voto. Estas mesas serán presididas, cada una, por un socio, actuando otro como auxiliar, debiendo ser todos ellos electores y designados por la Junta Electoral y fiscales titulares por cada lista oficializada. La mesa que a la hora fijada no contase con los fiscales titulares, funcionará con el Presidente o el suplente del mismo y a falta de estos con el socio que designe la Junta Electoral.

`r get_art_meta("141")`
* **Art. 141º**
El orden en el lugar de los comicios, lo mantendrán la Junta Electoral con los asociados o empleados que solicitare a la Comisión Directiva, del cual es responsable ante la misma.

`r get_art_meta("142")`
* **Art. 142º**
Inmediato a cada mesa, en el cuarto oscuro, el día de los comicios, deberán hallarse la o las boletas de los distintos candidatos, a disposición de cada votante, confeccionadas sobre papel blanco en tinta negra, sin propaganda alguna, donde se lea con claridad el nombre, apellido y número de asociado de los candidatos, como así también el cargo a que se postula.

`r get_art_meta("143")`
* **Art. 143º**
La votación será secreta, y cada votante, previo al depósito en la urna de la boleta, en sobre cerrado, exhibirá indefectiblemente su carnet societario y documento nacional de identidad.

`r get_art_meta("144")`
* **Art. 144º**
El presidente de la mesa estampará un sello con l a leyenda “votó” en el padrón. En caso de identidad dudosa, o que el votante no muestre su documento nacional de identidad o carnet de socio, el Presidente o los fiscales podrán observar o impugnar el voto.

`r get_art_meta("145")`
* **Art. 145º**
Los socios votarán por Presidente, Vicepresidente 1º, Vicepresidente 2º, Secretario General, Tesorero y once (11) candidatos a Vocales, por orden de lista, todos ellos para integrar la Comisión Directiva; seis (6) miembros titulares y tres (3) suplentes para integrar la Junta Representativa; y tres (3) miembros titulares y dos (2) miembros suplentes, para integrar la Comisión Revisora de Cuentas.

## Del Escrutinio

`r get_art_meta("146")`
* **Art. 146º**
A las dieciocho (18) horas, se clausurará la entrada a los comicios por el Presidente de la Junta Electoral y una vez que hayan votado los socios que aún se hallaren en el local, el Presidente de cada mesa procederá a abrir la urna y realizar el recuento de votos y de sobres. Una vez realizada esta operación se colocará nuevamente todas las boletas y sobres en l a urna, se cerrará ésta, se tapará la boca con una faja de papel que al efecto proveerá la Junta Electoral y llevará la firma de la autoridad de cada mesa. Acto seguido, el Presidente de la mesa labrará un acta en donde constará el número de sufragios emitidos, votos anulados, observados, como así también todas las observaciones que creyere conveniente anotar. Dichas actas, conjuntamente con las urnas, será llevadas por el Presidente de la mesa, que podrá ser acompañado por los fiscales de cada mesa, al lugar donde se constituya la mesa escrutadora, que estará integrada por los miembros de la Junta Electoral. Una vez recibidas todas las urnas, la junta escrutadora iniciará el recuento de votos y el escrutinio definitivo. Inmediatamente de finalizado el mismo, la Junta Electoral proclamará los candidatos triunfantes, labrándose el acta respectiva, la que será elevada al Presidente de la Comisión Directiva, para los efectos consiguientes.

`r get_art_meta("147")`
* **Art. 147º**
En caso de que dos o más listas hayan obtenido el mismo número de votos, en calidad de triunfantes, se convocará dentro de los quince (15) días siguientes, a una nueva elección con la intervención exclusiva de las agrupaciones que hayan igualado el número de sufragios.

`r get_art_meta("148")`
* **Art. 148º**
La Junta Electoral, en el caso de que fuera oficializada una sola lista procederá en el acto de apertura del comicio, a proclamarla, declarando así no haber necesidad del acto eleccionario.

`r get_art_meta("149")`
* **Art. 149º**
Dentro de los diez (10) días subsiguientes a la proclamación de los candidatos electos, éstos tomarán posición de sus cargos, cesando indefectiblemente los miembros salientes.
