# DE LA REVOCATORIA DE LOS MANDATOS

<div id="art150">
* **Art. 150º**
Cuando los socios dispongan aplicar el inciso m) del [artículo 32º](#art32), deberán solicitar por escrito la realización de un referéndum que determine la continuidad o no de las autoridades de la Institución. La solicitud ante el Presidente y por su intermedio a la Junta Representativa (con copia a Inspección de Personas Jurídicas), deberá estar acompañada por las firmas de un número de socios mayor al número de votos obtenidos por la lista mayoritaria en la última elección y no menor al 50% del total de socios que hayan sufragado. Además los firmantes deberán mantener la proporción de plenos y vitalicios de la última elección. Todas las firmas deberán estar certificadas por escribano público.

* **Art. 151º**
Tomada la decisión de convocar a referéndum, la Junta Representativa en un plazo no mayor de cinco días fijará la fecha de realización que no podrá ser mayor a los 60 días corridos ni menor a los treinta (30) días corridos. Designará una Junta Electoral que estará integrada por un presidente, un secretario, un secretario de actas, y por dos socios, uno coincidente con la propuesta que se lleva a referéndum y otro que no coincida. En este caso, los miembros de esta Junta Electoral deberán cumplir el requisito de tener diez (10) años de antigüedad ininterrumpida y como mínimo uno (1) de sus integrantes preferentemente deberán tener título de abogado.

* **Art. 152º**
Para que el referéndum tenga validez se establece que el número de votantes debe ser mayor al número total de votantes de la última elección de autoridades del club.

* **Art. 153º**
Se revocará el mandato de las autoridades cuando el número de votos por la revocatoria, sea mayor al 50 por ciento y a su vez no menor al número de votos que haya obtenido la lista mayoritaria en la última elección.

* **Art. 154º**
Si el resultado fuere la revocatoria del mandato de las autoridades, la Junta Representativa deberá convocar en un plazo no mayor a cinco (5) días corridos, a elecciones generales en un plazo no mayor de sesenta (60) días corridos y se regirá por todas las disposiciones establecidas en el capítulo de las elecciones.
