# DISPOSICIONES COMPLEMENTARIAS

`r get_art_meta("155")`
* **Art. 155º**
Estos estatutos entrarán a regir inmediatamente d e ser aprobados por la Asamblea convocada al efecto y por el Superior Gobierno de la Provincia, quedando la Comisión Directiva autorizada para solicitar su aprobación y aceptar modificaciones que este último hiciera.

`r get_art_meta("156")`
* **Art. 156º**
A partir de la aprobación de este Estatuto, se establece el “Día del Club”, el que será festejado anualmente en la fecha más próxima a la del Aniversario de la Institución (8 de agosto). En esa fecha, todos los asociados estarán obligados, para gozar de los espectáculos organizados por el Club, cualquiera fuere su naturaleza y demás beneficios que otorga la Institución, a abonar una contribución no menor de cincuenta (50) por ciento de la entrada general a los mencionados espectáculos.

`r get_art_meta("157")`
* **Art. 157º**
Queda la Comisión Directiva autorizada a fijar precios a los espectáculos deportivos y sociales que realizare en las instalaciones del Club, pudiendo establecer una contribución obligatoria a los asociados, no mayor del cincuenta (50) por ciento de la entrada a dichos espectáculos.

`r get_art_meta("158")`
* **Art. 158º**
Sin consentimiento previo de la Comisión Directiva, no podrá hacerse en el Club, suscripciones o cuestionarios de ninguna índole.

`r get_art_meta("159")`
* **Art. 159º**
Es potestad de la Comisión Directiva decidir el llamado a elecciones de manera anticipada, procediéndose a la realización del proceso eleccionario tal como está establecido en el articulado del [Capítulo XXIV](#cap24) del presente Estatuto.

`r get_art_meta("160")`
* **Art. 160º**
El personal administrativo, profesional o que perciba remuneración por cualquier concepto, sea o no socio, deberá mantener absoluta imparcialidad y prescindencia frente a los movimientos electorales de los asociados, bajo pena de cesantía. Además los que sean socios no podrán votar en Asambleas, Referéndum o elecciones ni ser electos para ningún cargo estatutario, hasta dos años después de haber cesado su cargo rentado.

`r get_art_meta("161")`
* **Art. 161º**
Es incompatible el cargo de Presidente y Secretario General o Presidente y Tesorero General, cuando entre los titulares de dichos cargos existiese una relación de parentesco hasta el cuarto grado de consanguinidad y segundo de afinidad.

`r get_art_meta("162")`
* **Art. 162º**
El presente estatuto deroga y anula toda disposición anterior que a él se oponga.
